### PR TITLE
Add docker-compose parameters for port numbers

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-api/issues/29

docker-compose.yaml: Add parameters for host port numbers

Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

### CODE REVIEW

**Comment by gctucker** [comment]
I guess this is the PR with some issues discussed in the daily meeting?

**Comment by JenySadadia** [comment]
> I guess this is the PR with some issues discussed in the daily meeting?

Yes.

**Comment by gctucker** [comment]
Is the only issue left about default values in `docker-compose.yaml`?

**Comment by JenySadadia** [comment]
> Is the only issue left about default values in `docker-compose.yaml`?

Yes.

**Comment by gctucker** [comment]
Well this seems to be working fine for me:
```diff
diff --git a/docker-compose.yaml b/docker-compose.yaml
index 757f27c4dbcc..cb9bc54e2e91 100644
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -15,7 +15,7 @@ services:
     volumes:
       - './api:/home/kernelci/api'
     ports:
-      - '${API_HOST_PORT}:8000'
+      - '${API_HOST_PORT:-8001}:8000'
     env_file:
       - '.env'
 
@@ -37,7 +37,7 @@ services:
     volumes:
       - './docker/storage/data:/usr/share/nginx/html'
     ports:
-      - ${STORAGE_HOST_PORT}:80
+      - ${STORAGE_HOST_PORT:-8002}:80
 
   ssh:
     container_name: 'kernelci-ssh'
@@ -47,7 +47,7 @@ services:
       - './docker/storage/data:/home/kernelci/data'
       - './docker/ssh/user-data:/home/kernelci/.ssh'
     ports:
-      - '${SSH_HOST_PORT}:22'
+      - '${SSH_HOST_PORT:-8022}:22'
 
 volumes:
   mongodata:
```

**Pull request merged**
