### PR TITLE
T35393 Add unit test for /token endpoint for Admin

### PR DESCRIPTION
**Pull request by JenySadadia**
Depends on https://github.com/kernelci/kernelci-api/pull/143

Unit test for /token endpoint to get token with admin scope for Admin user.

### CODE REVIEW

**Comment by gctucker** [comment]
Please rebase on top of #143 once it has been rebased. It's a large castle of cards but hopefully we'll get #140 and #141 merged soon to simplify the dependencies between PRs.

**Comment by gctucker** [comment]
Please rebase on top of #143 once it has been rebased, so we may be able to merge both PRs in a row.

**Review by mgalka — APPROVED** [review]

**Review by mgalka — APPROVED** [review]
lgtm

**Review by mgalka — APPROVED** [review]
lgtm

**Pull request merged**
