### PR TITLE
api.main: perform authorization for GET '/user/<id>'

### PR DESCRIPTION
**Pull request by JenySadadia**
Only allow authorized users to get user details matching given user ID to protect user's personal information.

### CODE REVIEW

**Comment by gctucker** [comment]
Looks like the client-side changes in `kernelci-core` got merged too early as they depend on this?

**Comment by nuclearcat** [comment]
There was patches related to /users endpoint, they are merged, and follow-up on similar issue, this and https://github.com/kernelci/kernelci-core/pull/2239 (not merged), another, /user/<id> endpoint.

**Comment by nuclearcat** [comment]
Tested on staging with https://github.com/kernelci/kernelci-core/pull/2239

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
