### PR TITLE
api.db: add `ne` operator

### PR DESCRIPTION
**Pull request by JenySadadia**
Support `ne`(not equal to) operator while querying objects from API.
e.g. `http://API_URL:8001/latest/nodes?name__ne=checkout` will fetch all the nodes except ones with name `checkout`.

### CODE REVIEW

**Comment by nuclearcat** [comment]
Isn't it already merged?
https://github.com/kernelci/kernelci-api/pull/357

**Comment by gctucker** [comment]
Yes it's quite puzzling how GitHub can have a PR to change a line that's already changed in the same way :thinking:

**Comment by gctucker** [comment]
@JenySadadia Your branch was based on an older revision that didn't have @nuclearcat's changes.  If you rebase than the changes in this PR disappear.

I would be interested to see how GitHub would manage that, like if we click on Merge now would it just mark it as "merged" without adding any actual commit to the branch?  I don't really need to find out...

**Comment by JenySadadia** [comment]
This is weird.
Bdw looking at https://github.com/kernelci/kernelci-api/pull/357, I was the one who tested the PR and yet I created another one :sweat_smile:

**Comment by JenySadadia** [comment]
It discarded my PR after rebase. The PR got closed automatically upon forced push.

**Pull request closed without merging**
