### PR TITLE
docker-compose.yaml: Update API to use docker image

### PR DESCRIPTION
**Pull request by nuclearcat**
Instead of doing local build - use docker image from registry.

### CODE REVIEW

**Comment by pawiecz** [comment]
I believe having a docker-compose doing a local build could still be useful for further development.

Do you think the main `docker-compose.yml` would be more frequently used for sample deployments and the one with adjustments for local builds should be renamed to e.g. `docker-compose-dev.yml` or would the development purposes be the main use case and there should be `docker-compose-production.yml` with image pulled from registry?

**Comment by nuclearcat** [comment]
current -dev is broken, this is what caused me to use docker image. But definitely i can rename old one to -dev and we can fix it for local development.

**Comment by pawiecz** [comment]
> current -dev is broken, this is what caused me to use docker image.

I'm a bit confused on what exactly was broken but it might not be relevant anymore.

> But definitely i can rename old one to -dev and we can fix it for local development.

Sure, let's keep them both (having the one with images from the registry as the default one). Later we could align them to keep only necessary overrides in the `-dev` (and call them [like on staging](https://github.com/kernelci/kernelci-deploy/blob/065097c9faa2227bbbfe99ccde891fcf1c059352/staging.kernelci.org#L358)).

**Comment by pawiecz** [comment]
Unit test were out-of-sync with current models in `kernelci-core`, hence failure. It should be all fine once this branch is rebased on current `main`.

**Review by JenySadadia — APPROVED** [review]
Tested OK locally.

**Comment by JenySadadia** [comment]
@nuclearcat Could you please rebase the PR? Hopefully, that would fix the unit tests.

**Comment by nuclearcat** [comment]
Done, i think it can be merged?

**Comment by JenySadadia** [comment]
> Done, i think it can be merged?

Yes, thanks.

**Pull request merged**
