### PR TITLE
[Close #1] Use motor instead of pymongo

### LINKED ISSUE #1: Use `motor` instead of `pymongo`
The initial implementation of `api.db` is based on `pymongo` to access the Mongo DB instance.  While this works fine, an alternative would be to use [`motor`](https://motor.readthedocs.io/en/stable/) which provides support for asynchronous queries.  This should help from a performance standpoint.

Here's an interesting Gist about migrating from `pymongo` to `motor`:
https://gist.github.com/anand2312/840aeb3e98c3d7dbb3db8b757c1a7ace

Steps:
- [ ] Follow the README to get an instance up and running with a user account
- [ ] Run some queries using `curl` to create and retrieve Thing objects
- [ ] Update `requirements.txt` to install `motor`
- [ ] Update the `api.db` implementation to rely on `motor`
- [ ] Run the same queries to create and retrieve Thing objects and check it's still working (as we don't have unit tests yet)
- [ ] Update `api.main` with the `async` keyword as appropriate
- [ ] Update `requirements.txt` to drop `pymongo`

Then create the following commits on a branch:
1. add `motor` to requirements
2. update `api.db` to use `motor`
3. use `async` in `api.main` where it's missing
4. drop `pymongo` from `requirements.txt`

Push this branch to a fork of `kernelci-api` and create a pull request.

### PR DESCRIPTION
**Pull request by mharyam**
close #1 

add motor to requirements
update api.db to use motor
use async in api.main where it's missing
drop pymongo from requirements.txt

### CODE REVIEW

**Comment by gctucker** [comment]
This replaces #12

**Comment by gctucker** [comment]
@mharyam Small typo in the git commit subject: "api: Update api.db to use motor" rather than "motors"

**Comment by mharyam** [comment]
> @mharyam Small typo in the git commit subject: "api: Update api.db to use motor" rather than "motors"

Hello @gctucker, 
I have updated it

**Comment by gctucker** [comment]
> > @mharyam Small typo in the git commit subject: "api: Update api.db to use motor" rather than "motors"
> 
> Hello @gctucker, I have updated it

Thanks, however I still see "motors" with the commit in the PR.  Did you do `git push --force` your branch after editing the commit message with `git commit --amend`?

**Comment by mharyam** [comment]
> > > @mharyam Small typo in the git commit subject: "api: Update api.db to use motor" rather than "motors"
> > 
> > 
> > Hello @gctucker, I have updated it
> 
> Thanks, however I still see "motors" with the commit in the PR. Did you do `git push --force` your branch after editing the commit message with `git commit --amend`?

This has been fixed now 
Thank you

**Review by gctucker — APPROVED** [review]
Tested OK locally with the login via /docs and pub/sub with api.client.

**Pull request merged**
