### PR TITLE
API unit test case for /me endpoint

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-api/issues/46

api/test_api.py: Add test case for /me endpoint

Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

### CODE REVIEW

**Review by mgalka — CHANGES_REQUESTED** [review]
The code looks good, but I think it needs to be rebased with the current main branch which has the /token endpoint test merged.

**Comment by JenySadadia** [comment]
> The code looks good, but I think it needs to be rebased with the current main branch which has the /token endpoint test merged.

Done rebasing and committed the changes.

**Comment by JenySadadia** [comment]
All tests are being PASSED on my local setup.
Need to check why pytest is failing here.

**Comment by gctucker** [comment]
Please rebase now that the GitHub checks have been fixed on the `main` branch.

**Comment by JenySadadia** [comment]
Git rebase is done @gctucker 
Mocked get_current_user function @mgalka

**Review by mgalka — APPROVED** [review]

**Pull request merged**
