### PR TITLE
Issue-15 Add Nginx Container as Storage, Add Readme.txt for healthcheck

### PR DESCRIPTION
**Pull request by BitWire**
This PR adds  a NGINX Container to the docker-compose, and a readme.txt for healthchecks as requested in Issue #15

### CODE REVIEW

**Comment by BitWire** [comment]
Will do, thanks for the explanation!

**Comment by BitWire** [comment]
Sorry for the late update, i had no access to a computer the last week.

**Comment by gctucker** [comment]
No problem.

There's a glitch in the commit message:
```
Signed-off-by: Thomas Schmidt <thomas.schmidt@gastfreund.net>>
Signed-off-by: Thomas Schmidt <thomas.schmidt@gastfreund.net>
```
So please drop the first line with the double `>>`.  Also it would be good to have something in the commit message explaining what it does.

Otherwise this is working fine, thanks!

**Comment by gctucker** [comment]
@BitWire If you want I can merge this and fix the glitch in the commit message as explained in my previous comment at the same time; let me know.

**Comment by BitWire** [comment]
You can now merge it

**Comment by gctucker** [comment]
OK thanks, I've merged the patch by hand as there was a problem with the series of commits in this PR.

**Pull request closed without merging**
