### PR TITLE
T35275 api/main.py: implement /user endpoint

### PR DESCRIPTION
**Pull request by JenySadadia**
Depends on https://github.com/kernelci/kernelci-api/pull/141

Develop an endpoint to create user with a
POST request.

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
I thought it was necessary to implement permissions first, to only allow "admin" users to use this kind of endpoint?

**Comment by JenySadadia** [comment]
Depends on https://github.com/kernelci/kernelci-api/pull/139

**Comment by JenySadadia** [comment]
> 

Actually, I need to take a look at the documentation for it.
First, I created an endpoint without any restrictions. I'll add permission verification now.

**Comment by JenySadadia** [comment]
Tested with the command:
```
curl -X 'POST' 'http://localhost:8001/user/jeny' -H 'accept: application/json'   -H 'Content-Type: application/json'  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0Iiwic2NvcGVzIjpbImFkbWluIiwidXNlciJdfQ.KhcIWfMRr3xTFSCLcr5L4KTUVSsfSsLeyRDEjgkQRBg' -d '{"password": "jeny"}'
```

**Comment by gctucker** [comment]
Please rebase.

**Comment by gctucker** [comment]
Please rebase now that #141 has been merged.

**Review by gctucker — APPROVED** [review]

**Pull request merged**
