### PR TITLE
Run kernelci-api test with Github Actions

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-api/issues/44

.github/workflows/main.yml: Added steps to run pytest for kernelci-api
api/__init__.py: Add file to make api a package
api/test_api.py: Add file with root endpoint test case
docker/api/requirements-dev.txt: Add file with python test packages

Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

### CODE REVIEW

**Comment by JenySadadia** [comment]
I tested the patch on ```add-test-github-actions``` branch. Below is the URL for the Github action results:
https://github.com/JenySadadia/kernelci-api/actions/runs/1586298870

**Comment by JenySadadia** [comment]
Pushed code with ```installPackagesDev.sh``` script to install python packages.
Latest testing result is on: https://github.com/JenySadadia/kernelci-api/actions/runs/1590761809

**Comment by mgalka** [comment]
I think this PR needs a rebase with current kernelci/main before it can be merged

**Comment by JenySadadia** [comment]
I rebased onto main and committed the changes. 
Please check @mgalka

**Comment by mgalka** [comment]
lgtm

**Pull request merged**
