### PR TITLE
Bug fix: admin users with duplicate email

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-api/issues/444
Created on top of https://github.com/kernelci/kernelci-api/pull/436

Staging has multiple users with the same email address. Fix the bug in admin user setup script.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
LGTM, staging seems works fine

**Comment by nuclearcat** [comment]
It looks like it need rebase now?

**Comment by JenySadadia** [comment]
@nuclearcat  Could you please update email of `staging.kernelci.org` or `admin` user on staging as both have the same emails?

**Comment by nuclearcat** [comment]
Done, but i set non-existing email for admin. I guess it's ok for now, for staging

**Comment by JenySadadia** [comment]
> Done, but i set non-existing email for admin. I guess it's ok for now, for staging

Yes, it will work for now.

**Pull request merged**
