### PR TITLE
T39722 Improve exception handling

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-api/issues/201
Depends on https://github.com/kernelci/kernelci-api/pull/200

Improved exception handling using global exception handlers for `ValueError` and `errors.invalidId`.
Also, improved exception handling for `PubSub` related methods.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Rebased it.

**Comment by mgalka** [comment]
@JenySadadia It looks some tests are not happy

**Comment by JenySadadia** [comment]
> @JenySadadia It looks some tests are not happy

The test was failing as the versioned API instance (it is a sub-application created under the hood by `fastapi-versioning`) is not able to use global exception handlers defined for the main app.
The issue has already been reported here: https://github.com/DeanWay/fastapi-versioning/issues/30
Added a workaround to fix it.

**Comment by JenySadadia** [comment]
Tested OK on staging:

```
$ curl https://staging.kernelci.org:9000/latest/nodes?state=not_done
{"detail":"Invalid state value 'not_done'"}
```
```
$ curl https://staging.kernelci.org:9000/latest/get_root_node/6332d8f51a45d41c279e7a0
{"detail":"'6332d8f51a45d41c279e7a0' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string"}
```
```
$ curl https://staging.kernelci.org:9000/latest/get_root_node/6332d8f51a45d41c279e7a02
{"detail":"Node not found with id: 6332d8f51a45d41c279e7a02"}
```

**Comment by gctucker** [comment]
> Tested OK on staging:

Could you please also provide the HTTP codes returned by these queries?  I think there may be a curl option to print them.  Otherwise there's always `--verbose` or `-I` but this one doesn't show the full response.

**Comment by JenySadadia** [comment]
> > Tested OK on staging:
> 
> Could you please also provide the HTTP codes returned by these queries? I think there may be a curl option to print them. Otherwise there's always `--verbose` or `-I` but this one doesn't show the full response.

Sure. Below are the verbose responses for above queries:

```
$ curl -i https://staging.kernelci.org:9000/latest/nodes?state=not_done
HTTP/2 400 
server: nginx
date: Tue, 07 Feb 2023 13:16:23 GMT
content-type: application/json
content-length: 43

{"detail":"Invalid state value 'not_done'"}
```

```
$ curl -i https://staging.kernelci.org:9000/latest/get_root_node/6332d8f51a45d41c279e7a0
HTTP/2 400 
server: nginx
date: Tue, 07 Feb 2023 13:18:39 GMT
content-type: application/json
content-length: 119

{"detail":"'6332d8f51a45d41c279e7a0' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string"}
```

```
$ curl -i https://staging.kernelci.org:9000/latest/get_root_node/6332d8f51a45d41c279e7a02
HTTP/2 404 
server: nginx
date: Tue, 07 Feb 2023 13:19:04 GMT
content-type: application/json
content-length: 61

{"detail":"Node not found with id: 6332d8f51a45d41c279e7a02"}
```

**Review by mgalka — APPROVED** [review]

**Pull request merged**
