### PR TITLE
doc: update Early Access page with latest kci

### PR DESCRIPTION
**Pull request by gctucker**
Update the Early Access setup documentation page with the reworked kci command line syntax and related TOML settings.

Fixes https://github.com/kernelci/kernelci-core/issues/2158

### CODE REVIEW

**Comment by gctucker** [comment]
Deployed OK on staging: https://static.staging.kernelci.org/docs/api/early-access/

**Review by JenySadadia — APPROVED** [review]
`User` part looks good to me.
Someone else should review `Storage` related changes.

**Review by nuclearcat — APPROVED** [review]
LGTM

**Comment by nuclearcat** [comment]
I will try to use these changes for new deployment

**Comment by gctucker** [comment]
Oh no it was too early to merge this, the code changes aren't merged yet.  I'll send a revert.

**Comment by gctucker** [comment]
OK I've pushed a revert for this commit, will open a new PR now.

**Pull request merged**
