### PR TITLE
viewer.html: Add to job platform

### PR DESCRIPTION
**Pull request by nuclearcat**
It is highly useful to see which platform (usuall DUT type) test is scheduled.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Shouldn't it be a different column?

**Comment by nuclearcat** [comment]
Yes, i can do that, it was just hack to resolve current issue.

**Comment by nuclearcat** [comment]
Tested on staging

**Comment by JenySadadia** [comment]
Test nodes don't display platform info. Is that intentional?
https://staging.kernelci.org:9000/viewer?search=parent%3D667397067e95224939eeb88b

**Comment by JenySadadia** [comment]
> Test nodes don't display platform info. Is that intentional? https://staging.kernelci.org:9000/viewer?search=parent%3D667397067e95224939eeb88b

Looks like the logic only includes job nodes.

**Review by JenySadadia — APPROVED** [review]

**Pull request merged**
