### PR TITLE
Update user model

### PR DESCRIPTION
**Pull request by JenySadadia**
api.main: add PUT '/user/<username>' endpoint
    
Implement a handler to update user models. Only admin users will be allowed to access this endpoint and be able to
update other user models. All user fields except password can be updated using this handler.

Depends on #353

### CODE REVIEW

**Comment by nuclearcat** [comment]
Is there other way how admin can update user password? Sometimes they might forget their passwords.

**Comment by gctucker** [comment]
I guess we should have a solution for users to reset their passwords via email.

**Comment by JenySadadia** [comment]
> Is there other way how admin can update user password? Sometimes they might forget their passwords.

Admins shouldn't be able to reset other users' passwords for the sake of security.
I agree with Guillaume that we should implement a different mechanism for it.

**Comment by gctucker** [comment]
Note: For the Early Access phase, it's already possible to replace a password via the MongoDB shell.  I just don't think we should be adding an API feature for this as a production solution.  Let's see if some fully-fledged user account packages for FastAPI can handle all this out of the box.

**Comment by gctucker** [comment]
@JenySadadia Is this PR based on top of #353 or does it replace it?

**Comment by JenySadadia** [comment]
> @JenySadadia Is this PR based on top of #353 or does it replace it?

Yes, created on top of #353 to avoid merge conflicts.

**Comment by JenySadadia** [comment]
`kci` command from https://github.com/kernelci/kernelci-core/pull/2103 can be used to test this PR.

**Review by gctucker — APPROVED** [review]
OK I guess we're good to merge this now, and later this will probably reworked with fastapi-users.

**Pull request merged**
