### PR TITLE
doc: improve user-related documentation

### PR DESCRIPTION
**Pull request by JenySadadia**
Improve documentation of `early-access` and `local-instance` guides.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Looks OK on staging https://static.staging.kernelci.org/docs/api/

**Review by gctucker — COMMENTED** [review]
Presumably this depends on the new user management scheme to first be deployed in on the the early-access instance.  Is there a GitHub issue to follow the status of this?

**Comment by JenySadadia** [comment]
> Presumably this depends on the new user management scheme to first be deployed in on the the early-access instance. Is there a GitHub issue to follow the status of this?

I don't think we have one. @nuclearcat can confirm though.

**Comment by JenySadadia** [comment]
I think this should be merged now as the new user management scheme has been deployed to `early-access` instance by @nuclearcat.

**Comment by nuclearcat** [comment]
LGTM

**Pull request merged**
